version: '3.9'
services:
  app:
    build: .
    container_name: app
    image: app
    environment:
      TWITTER_BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAJCwdQEAAAAAUVUPc7n4rDIcuKh%2B3VTh4QEggcE%3Dc5KOibfFoFnVgYrWROdoyCYqEbZqbl6iEcZMK2QIe5l2NFCi1E'
    ports:
      - 8080:8080

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app
